DEFAULT_TEACHER_STUDENT_PARAMS = {
    "env_id": "CartPole-v1",
    "num_epochs": 10,
    "train_batch_size": 2000,
    "rollout_fragment_length": 500,
    "num_rollout_workers": 4,
    "student_lr": 1e-4,
    "student_hidden_dim": 128,
    "student_hidden_depth": 2,
    "student_use_residual": True,
    "teacher_lr": 1e-4,
    "teacher_hidden_dim": 2048,
    "teacher_hidden_depth": 8,
    "teacher_use_residual": True,
    "clip_param": 0.2,
    "value_loss_coeff": 1.0,
    "entropy_coeff": 0.0,
    "max_grad_norm": 1.0,
    "device": "cpu",
    "log_dir": "logs/teacher_student",
    "seed": 42,
    "teacher_eval_episodes": 1,
    "lr_decay": {
        "enabled": True,
        "gamma": 0.5,
        "step_epochs": 100,
        "min_lr": 1e-6,
    },
}
